export const EMAIL_CHANGED = 'email_changed'
export const PASSWORD_CHANGED = 'password_changed'
export const SIGNUP_USER_START = 'signup_user_start'
export const SIGNUP_USER_FAIL = 'signup_user_fail'
export const SIGNUP_USER_SUCCESS = 'signup_user_success'